### ISSUE TITLE
Splitting the crate into a sys and a high level crate

### ISSUE THREAD

**Issue by hellow554** [Hakuyume/socketcan-rs#22]
Currently, there's a lot of low level stuff going on in the API, for example passing a `CString` as an argument for the device. Also a lot of unsafe places are around.

To circumvent this, people tend to create a `-sys` crate and on top of that they build a rusty interface.

E.g. https://crates.io/crates/rusb depends on https://crates.io/crates/rusb

This way you could split up the `build.rs` and `sys.rs` thingy into its own crate and build on top of that a better API, that would accept a `&str` for example. 

There are a few scary places that I can't get my head of, and sadly miri can't help here either, because of the `libc` calls. 

What do you think about this? Is that something you want to spend your time on? Do you want help for that? What is your goal with this crate?

**Comment by Hakuyume** [comment]
I think you are talking about three topics.

1. Make `-sys` crate for bindgen-generated code.
I agree with you that making `-sys` crate is common in Rust. There is no strong reason for a unified crate (except the crate's name).

2. Internal code contains a lot of unsafe blocks and libc calls.
`-sys` crate won't help this because current `sys.rs` contains only structs and constants. Even if I make a `-sys` crate, I have to call `libc` and its APIs are unsafe. `rusb` also contains a lot of unsafe code.

3. The public APIs are not enough high-level (e.g. taking `&CStr` instead of `&str`).
This is intentional. `&Cstr` can avoid unnecessary conversion when I retrieve an ifname for other low-level APIs. I don't want to do CString -> String -> CString conversion.
